import os

html_dir = "src/HTML"
output_dir = "src/HTML"
include_all_path = os.path.join(output_dir, "_include_all.h")

html_files = [f for f in os.listdir(html_dir) if f.endswith(".html")]

include_lines = []

for html_file in html_files:
    filepath = os.path.join(html_dir, html_file)
    with open(filepath, "r", encoding="utf-8") as f:
        content = f.read()

    basename = os.path.splitext(html_file)[0]    # es. "index.html" -> "index"
    h_filename = f"{basename}.h"
    h_filepath = os.path.join(output_dir, h_filename)

    # Scrive il file header
    with open(h_filepath, "w", encoding="utf-8") as f:
        f.write(f'// Autogenerated from {html_file}\n')
        f.write(f'const char PAGE_{basename}[] PROGMEM = R"rawliteral(\n')
        f.write(content)
        f.write('\n)rawliteral";\n')

    print(f"Generato {h_filepath}")
    include_lines.append(f'#include "{h_filename}"')

# Scrive il file _include_all.h
with open(include_all_path, "w", encoding="utf-8") as f:
    f.write("// Header che include tutte le pagine generate\n")
    for line in include_lines:
        f.write(line + "\n")

print(f"Generato {include_all_path}")
